Bug/tg 236 added missing chkbox
garage-it/SmartHouse-frontend pull request #130
Opened 2016-11-06 09:53 UTC by Appius

- Added "servo" checkbox to add/edit device page.
- Minor fixes:
   - Renamed .css file to .scss;
   - Fix wrongly referenced labels on the page.

2016-11-06 09:53 UTC, review-ninja commented
<a href="https://app.review.ninja/garage-it/SmartHouse-frontend/pull/130" target="_blank"><img src="https://app.review.ninja/54199806/pull/130/badge" alt="ReviewNinja"/>

2016-11-06 12:50 UTC, borys-ihnatyev requested changes
PR looks fine, besides few minor issues.

2016-11-06 12:50 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
There is no async stuff to call **done**, you can totally remove done from arguments

2016-11-06 12:50 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
There is no async stuff to call **done**, you can totally remove done from arguments

2016-11-06 12:50 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
There is no async stuff to call **done**, you can totally remove done from arguments

2016-11-06 12:50 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +            if (chkType === 'executor') {
It would be more gracefully to use enum instead of string, such solution would force you to avoid magic values in the code.

2016-11-06 12:51 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!fix

2016-11-06 12:51 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!fix

2016-11-06 12:51 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +            if (chkType === 'executor') {
!fix

2016-11-06 12:53 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="servo">
do we need this **id** attribute ?

2016-11-06 12:54 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="executor">
do we need this **id** attribute ?

2016-11-06 12:55 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +        if (this.sensor.executor && this.sensor.servo) {
I would rather split this into two functions **validateServo** and **validateExecutor**, as it is possible to use them separately in template

2016-11-06 13:33 UTC, stremann commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #executor, #servo {
do not use IDs for styling UI

2016-11-06 13:34 UTC, stremann commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #servo { margin-left: 15px; }
do not use IDs for styling UI

2016-11-06 19:35 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +        if (this.sensor.executor && this.sensor.servo) {
And if we can't check two values, it would preferable to use select or radio input

2016-11-06 19:40 UTC, borys-ihnatyev commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #servo { margin-left: 15px; }
We use BEM metodology, which disallow use ids, all selectors should be classes, 
https://ru.bem.info/methodology/css/#Селекторы

2016-11-07 09:11 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!resolved

2016-11-07 09:11 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
ok, got it.

2016-11-07 09:12 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
fixed

2016-11-07 09:12 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
fixed

2016-11-07 09:12 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!resolve

2016-11-07 09:13 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +        if (this.sensor.executor && this.sensor.servo) {
Agree.
Updated with two functions.

2016-11-07 09:15 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +        if (this.sensor.executor && this.sensor.servo) {
I am not sure. That's different options, the fact that both checkboxes cannot be checked at the same time is just a business rule.

2016-11-07 09:16 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +            if (chkType === 'executor') {
For now, there are two different functions. Not relevant.

2016-11-07 09:16 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +            if (chkType === 'executor') {
!resolve

2016-11-07 09:17 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!fixed

2016-11-07 09:17 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.test.ts
> +        done();
!fixed

2016-11-07 09:17 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.component.ts
> +            if (chkType === 'executor') {
!resolved

2016-11-07 09:17 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #executor, #servo {
!fixed

2016-11-07 09:18 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #servo { margin-left: 15px; }
!fixed

2016-11-07 09:18 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="executor">
!completed

2016-11-07 09:18 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="servo">
!completed

2016-11-07 09:21 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="servo">
!resolved. Changed it to 'class' attribute.

2016-11-07 09:21 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.template.html
> +        <div id="executor">
!resolved. Changed it to 'class' attribute.

2016-11-07 09:22 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #executor, #servo {
!fixed. thanks!

2016-11-07 09:22 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.style.scss
> +        #servo { margin-left: 15px; }
!fixed. thanks!

2016-11-07 09:49 UTC, piton13 commented on src/app/devices/sensor-details/sensor-detail.template.html
> +    <div style="padding-bottom: 10px;">
!fix will be better to avoid using inline styles;

2016-11-07 10:37 UTC, Appius commented on src/app/devices/sensor-details/sensor-detail.template.html
> +    <div style="padding-bottom: 10px;">
!fixed thanks!

2016-11-07 11:02 UTC, borys-ihnatyev approved these changes

2016-11-07 11:03 UTC, merged